# Generated by Django 5.2 on 2025-04-19 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('course_code', models.SmallIntegerField()),
                ('major_code', models.CharField(choices=[('907', '907'), ('705', '705'), ('302', '302'), ('401', '401')], max_length=20)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('input_form', models.TextField()),
                ('output_form', models.TextField()),
                ('question_file', models.FileField(upload_to='')),
                ('timelimit', models.SmallIntegerField()),
                ('inputs_file', models.FileField(upload_to='')),
                ('outputs_file', models.FileField(upload_to='')),
                ('language', models.CharField(choices=[('python', 'python'), ('c++', 'c++'), ('c#', 'c#'), ('java', 'java')], max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(auto_now_add=True)),
                ('score', models.FloatField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questions.course')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
