# Generated by Django 5.2 on 2025-04-20 06:21

import Questions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='inputs_file',
            field=models.FileField(upload_to=Questions.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='question',
            name='outputs_file',
            field=models.FileField(upload_to=Questions.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_file',
            field=models.FileField(upload_to=Questions.models.user_directory_path),
        ),
    ]
