# Generated by Django 5.2 on 2025-05-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0004_alter_question_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='allowed_number',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
