# Generated by Django 5.2 on 2025-05-21 10:45

import Questions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0005_question_allowed_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_file',
            field=models.FileField(blank=True, upload_to=Questions.models.user_directory_path),
        ),
    ]
