# Generated by Django 5.2 on 2025-05-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0006_alter_question_question_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='language',
            field=models.CharField(choices=[('python', 'python'), ('c#', 'c#'), ('java', 'java')], max_length=10),
        ),
    ]
