# Generated by Django 5.2 on 2025-05-03 09:11

import Judge.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Judge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='solution_file',
            field=models.FileField(upload_to=Judge.models.user_directory_path),
        ),
    ]
