# Generated by Django 5.2 on 2025-05-07 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Judge', '0004_contest_contester'),
        ('Questions', '0004_alter_question_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestSubmissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('tries', models.SmallIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questions.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Judge.contester')),
            ],
        ),
    ]
