# Generated by Django 5.2 on 2025-05-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Judge', '0005_contestsubmissions'),
        ('Questions', '0004_alter_question_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='questions',
        ),
        migrations.AddField(
            model_name='contest',
            name='questions',
            field=models.ManyToManyField(to='Questions.question'),
        ),
    ]
