# Generated by Django 5.2 on 2025-05-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Judge', '0006_remove_contest_questions_contest_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='contester',
            name='questions',
            field=models.JSONField(default={}),
        ),
    ]
