# Generated by Django 5.2 on 2025-05-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Judge', '0007_contester_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='is_contest',
            field=models.BooleanField(default=False),
        ),
    ]
