# Generated by Django 5.2 on 2025-04-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0002_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mobilephone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
