# Generated by Django 5.2 on 2025-04-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0003_customuser_mobilephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('0', 'Teacher'), ('1', 'Student')], default='student', max_length=7),
        ),
    ]
