# Generated by Django 5.2 on 2025-04-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nationalcode',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
