# Generated by Django 5.2 on 2025-05-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0006_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('0', 'Teacher'), ('1', 'Student')], default='student', max_length=7),
        ),
    ]
